### ISSUE TITLE
adjusting app code for specific RFID functions

### ISSUE THREAD

**Issue by trevorcmit** [cslrfid/CS108-Mobile-CSharp-DotNetStd-App#11]
Hello CSL,

I've been working with the CS108-Mobile-CSharp-DotNetStd-App code for a few days now, working with Visual Studio 2022 and the CS108RFIDReader.sln project with the BLE.Client.Droid code, running on an external Android device connected with USB (not an android emulator). 

One goal I have is to adjust the existing RFID scanning code to run on a regular interval, in the range of 5-10 minutes between scans for the RFID chips. These chips would mostly be temperature sensing chips, so they would use the _Special Func_ tab on the CS108 app. Additionally, has CSL done anything in regards to plotting within the app? I'm looking to track the values of the RFID temperature scans over time, and graph them if possible. 

Is there any suggestions on how one could go about adding these adjustments? I'm new to Xamarin and this form of C# development so just looking for pointers or tips to direct the development of these features.

Thank you!

**Comment by ksclam** [comment]
This repository has been depreciated and all code is now at the v4 repository with updated libraries and framework:

https://github.com/cslrfid/CS108-Mobile-CSharp-DotNetStd-App-v4

For any product support, please contact CSL directly
https://www.convergence.com.hk/contact-csl/  

Thanks.
